Phase 1/color
brandonberney/research-and-innovation pull request #24
Opened 2020-10-14 21:17 UTC by Erika-Maglasang

A made a branch that is a copy of the phase 1 footer pull request #21. 

Fixes #

- Applied the black to red fade on the body of the layout page, but the actual rule is located in the index page.

- The background image covers the whole page, thanks to the flex command.

- The background also has it's own stylesheet if we need to take it off of the index page.

Link to what the page looks like:
https://localhost:44367/

2020-10-14 21:37 UTC, brandonberney requested changes
It’s typically best-practice to only create branches off of master. I will set up ASP.NET to support hosting css files and from there we can add in your code.

2020-10-14 23:26 UTC, brandonberney approved these changes

2020-10-14 23:27 UTC, brandonberney commented
Code has been updated to use static files and apply across all pages. I give this the green light now. 👍🏼

2020-10-16 04:03 UTC, Erika-Maglasang reviewed
Link to what the website looks like after color changes have been applied:
https://localhost:44367/

LayoutColor contains all the stylesheet code.

2020-10-16 04:07 UTC, Erika-Maglasang commented
> Link to what the website looks like after color changes have been applied:
> https://localhost:44367/
> 
> LayoutColor contains all the stylesheet code.

![Screenshot 2020-10-16 00 05 20](https://user-images.githubusercontent.com/72048107/96211882-7d0a8900-0f43-11eb-83c8-6a720f4514ba.png)

2020-10-16 17:26 UTC, brandonberney requested changes
Please see my comments regarding the footer.

2020-10-16 17:26 UTC, brandonberney commented on CardTech.ResearchSite/CardTech.ResearchSite/Pages/Shared/_Layout.cshtml
> +                        <a class="footer-link"href="#">Login</a>
I would remove `class="footer-link"`

2020-10-16 17:26 UTC, brandonberney commented on CardTech.ResearchSite/CardTech.ResearchSite/Pages/Shared/_Layout.cshtml
> +                        <a class="footer-link"href="#">Register</a>
I would remove `class="footer-link"`

2020-10-16 17:26 UTC, brandonberney commented on CardTech.ResearchSite/CardTech.ResearchSite/Pages/Shared/_Layout.cshtml
> +                                <a class="footer-link"href="tel:+15028526512">(502) 852-6512</a>
I would remove `class="footer-link"`

2020-10-16 17:26 UTC, brandonberney commented on CardTech.ResearchSite/CardTech.ResearchSite/Pages/Shared/_Layout.cshtml
> +                                <a class="footer-link"href="tel:+15028528361">(502) 852-8361</a>
I would remove `class="footer-link"`

2020-10-16 17:26 UTC, brandonberney commented on CardTech.ResearchSite/CardTech.ResearchSite/Pages/Shared/_Layout.cshtml
> +                                <a class="footer-link"href="https://twitter.com/UofLInnovate" target="_blank">Twitter</a>
I would remove `class="footer-link"`

2020-10-16 17:26 UTC, brandonberney commented on CardTech.ResearchSite/CardTech.ResearchSite/Pages/Shared/_Layout.cshtml
> +                                <a class="footer-link"href="https://www.facebook.com/UofLInnovate" target="_blank">Facebook</a>
I would remove `class="footer-link"`

2020-10-16 17:26 UTC, brandonberney commented on CardTech.ResearchSite/CardTech.ResearchSite/Pages/Shared/_Layout.cshtml
> +                                <a class="footer-link"href="https://www.linkedin.com/school/uoflinnovate/" target="_blank">LinkedIn</a>
I would remove `class="footer-link"`

2020-10-16 17:26 UTC, brandonberney commented on CardTech.ResearchSite/CardTech.ResearchSite/Pages/Shared/_Layout.cshtml
> +                                <a class="footer-link"href="#">Students</a>
I would remove `class="footer-link"`

2020-10-16 17:26 UTC, brandonberney commented on CardTech.ResearchSite/CardTech.ResearchSite/Pages/Shared/_Layout.cshtml
> +                                <a class="footer-link" href="#">Community</a>
I would remove `class="footer-link"`

2020-10-16 17:26 UTC, brandonberney commented on CardTech.ResearchSite/CardTech.ResearchSite/Pages/Shared/_Layout.cshtml
> +                                <a class="footer-link" asp-page="/Industry">Industry</a>
I would remove `class="footer-link"`

2020-10-16 17:26 UTC, brandonberney commented on CardTech.ResearchSite/CardTech.ResearchSite/Pages/Shared/_Layout.cshtml
> +                                <a class="footer-link" asp-page="/Research">Researchers</a>
I would remove `class="footer-link"`

2020-10-16 17:26 UTC, brandonberney commented on CardTech.ResearchSite/CardTech.ResearchSite/wwwroot/css/LayoutColor.css
> +.nav, .nav-item, .nav-link, .footer-item, .footer-link{
You should add in a class that reads

`
.footer a {
    color: white;
}
`

Which will remove the need for adding individual classes to each link.

2020-10-16 17:46 UTC, brandonberney commented on CardTech.ResearchSite/CardTech.ResearchSite/Pages/Shared/_Layout.cshtml
> +                        <a class="footer"href="#">Login</a>
Sorry if I wasn't clear, but there shouldn't be **any** class on these tags.

2020-10-16 17:50 UTC, Erika-Maglasang commented
I took away the footer-link class and replaced it with the existing footer class. At first I tried to apply the class to the whole footer, but it only applied it to the header text. Would it be better to place it in the div, p, or the col-lg-1 - 6? Is there an easier way to override the default blue link color?

2020-10-16 18:08 UTC, Erika-Maglasang commented
![Screenshot 2020-10-16 14 05 07](https://user-images.githubusercontent.com/72048107/96293425-b8936a80-0fb8-11eb-9eb0-3be3ad032fc0.png)

All links on the footer will be left as the default blue for the time being.

2020-10-16 18:45 UTC, brandonberney commented
> I took away the footer-link class and replaced it with the existing footer class. At first I tried to apply the class to the whole footer, but it only applied it to the header text. Would it be better to place it in the div, p, or the col-lg-1 - 6? Is there an easier way to override the default blue link color?

The fix was:

`
footer a {
color: white;
}`

I've committed this change.

2020-10-16 21:36 UTC, GMStull approved these changes
Looks solid to me, no issues.

2020-10-16 21:54 UTC, brandonberney commented
Two issues I've noticed in mobile:

1. The button that normally appears on the header is now missing.

2. The rounded corners looks ugly on mobile. We should probably use an entirely white background in this environment.

<img width="341" alt="image" src="https://user-images.githubusercontent.com/7992425/96311917-85f96a00-0fd8-11eb-8045-f715a9e8625a.png">

2020-10-17 00:32 UTC, JCDILL03 approved these changes
The code looks good to me... especially everything with the colors and columns

2020-10-17 20:52 UTC, brandonberney requested changes
Little confused by the commit made by @GMStull. Please see the comments I left.

2020-10-17 20:52 UTC, brandonberney commented on CardTech.ResearchSite/CardTech.ResearchSite/Pages/About.cshtml
> +<body>
I'm having trouble understanding this... is there a reason we have some sample code here?

2020-10-17 20:52 UTC, brandonberney commented on CardTech.ResearchSite/CardTech.ResearchSite/wwwroot/css/LayoutColor.css
> +.row {
These are already classes in bootstrap. Is this relevant/does it interfere?

2020-10-17 21:59 UTC, brandonberney approved these changes
Good for now, will make additional changes in `enhancement/*` branches as needed. Merging.

2020-10-17 22:00 UTC, merged